#run the command "xhost +" before run "docker-compose up"
version: "3"
services:
  jewelerygui:
    build: .
    environment:
      DISPLAY: 172.26.0.1:0.0 #xserver installation required-host ipv4
    #volumes:
    #      - $HOME/.Xauthority:/root/.Xauthority:rw
    depends_on:
      - "postgres-db"
    networks:
      - default

  postgres-db:
    image: postgres:10
    hostname: postgres-db
    container_name: db-postgres
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - default
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./code/Database_Tables2.0.sql:/docker-entrypoint-initdb.d/Database_Tables2.0.sql
    environment:
      - "POSTGRES_PASSWORD=kostas581994"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=jewelery"
    restart: always
 
volumes:
  db-data:
    driver: local